name: EMCTools
version: ${project.version}
description: ${project.description}
api-version: '1.13'
author: creatorfromhell, KarlofDuty
website: http://karlofduty.com
load: POSTWORLD
main: com.karlofduty.EMCTools.EMCTools
permissions:
  emc.joinqueue:
    description: Lets a player join the bungeecord queue.
    default: op
commands:
  joinqueue:
    description: Joins the queue to a server.
    usage: /joinqueue <server name>
  beta:
    description: Joins the beta server.
    usage: /beta
  premium:
    description: Shows premium information.
    usage: /premium
  towny:
    description: Joins the towny server.
    usage: /towny