name: EMCTools
version: ${project.version}
description: ${project.description}
api-version: '1.16'
author: creatorfromhell, KarlofDuty
website: http://karlofduty.com
load: POSTWORLD
main: com.karlofduty.EMCTools.EMCTools
commands:
  premium:
    description: Shows premium information.
    usage: /premium
  map:
    description: Sends a clickable message that opens the map.
  docs:
    description: Sends the user a link for the earthmc docs.
    usage: /docs
  support:
    description: Sends the user a link for the earthmc support discord.
    usage: /support
  wiki:
    description: Sends the user a link for the earthmc wiki.
    usage: /wiki